include: package:lint/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Don't find it necessary.
    always_use_package_imports: false
